import type { Game } from "../types";

export const FALLBACK_GAMES: Game[] = [
  { id: 1, slug: "grand-theft-auto-san-andreas", title: "Grand Theft Auto: San Andreas", normalized_title: "grand theft auto: san andreas", original_release_year: 2004, original_platform: "PS2 / Android", created_at: new Date(), updated_at: new Date() },
  { id: 2, slug: "max-payne", title: "Max Payne", normalized_title: "max payne", original_release_year: 2001, original_platform: "PC / Android", created_at: new Date(), updated_at: new Date() },
  { id: 3, slug: "fallout-2", title: "Fallout 2", normalized_title: "fallout 2", original_release_year: 1998, original_platform: "PC", created_at: new Date(), updated_at: new Date() },
  { id: 4, slug: "hollow-knight", title: "Hollow Knight", normalized_title: "hollow knight", original_release_year: 2017, original_platform: "PC", created_at: new Date(), updated_at: new Date() },
  { id: 5, slug: "diablo", title: "Diablo (DevilutionX)", normalized_title: "diablo (devilutionx)", original_release_year: 1996, original_platform: "PC", created_at: new Date(), updated_at: new Date() },
  { id: 6, slug: "super-mario-64", title: "Super Mario 64", normalized_title: "super mario 64", original_release_year: 1996, original_platform: "N64", created_at: new Date(), updated_at: new Date() },
  { id: 7, slug: "grand-theft-auto-vice-city", title: "Grand Theft Auto: Vice City", normalized_title: "grand theft auto: vice city", original_release_year: 2002, original_platform: "PS2 / Android", created_at: new Date(), updated_at: new Date() },
  { id: 8, slug: "grand-theft-auto-iii", title: "Grand Theft Auto III", normalized_title: "grand theft auto iii", original_release_year: 2001, original_platform: "PS2 / Android", created_at: new Date(), updated_at: new Date() },
  { id: 9, slug: "bully-anniversary-edition", title: "Bully: Anniversary Edition", normalized_title: "bully: anniversary edition", original_release_year: 2006, original_platform: "PS2 / Android", created_at: new Date(), updated_at: new Date() },
  { id: 10, slug: "the-simpsons-hit-and-run", title: "The Simpsons: Hit & Run", normalized_title: "the simpsons: hit & run", original_release_year: 2003, original_platform: "PS2 / GameCube", created_at: new Date(), updated_at: new Date() },
  { id: 11, slug: "fallout-1", title: "Fallout 1", normalized_title: "fallout 1", original_release_year: 1997, original_platform: "PC", created_at: new Date(), updated_at: new Date() },
  { id: 12, slug: "dead-space-mobile", title: "Dead Space Mobile", normalized_title: "dead space mobile", original_release_year: 2011, original_platform: "Android / iOS", created_at: new Date(), updated_at: new Date() },
  { id: 13, slug: "mass-effect-infiltrator", title: "Mass Effect Infiltrator", normalized_title: "mass effect infiltrator", original_release_year: 2012, original_platform: "Android / iOS", created_at: new Date(), updated_at: new Date() },
  { id: 14, slug: "sonic-mania", title: "Sonic Mania", normalized_title: "sonic mania", original_release_year: 2017, original_platform: "PC", created_at: new Date(), updated_at: new Date() },
  { id: 15, slug: "half-life", title: "Half-Life", normalized_title: "half-life", original_release_year: 1998, original_platform: "PC", created_at: new Date(), updated_at: new Date() },
  { id: 16, slug: "return-to-castle-wolfenstein", title: "Return to Castle Wolfenstein", normalized_title: "return to castle wolfenstein", original_release_year: 2001, original_platform: "PC", created_at: new Date(), updated_at: new Date() },
  { id: 17, slug: "doom-3", title: "Doom 3", normalized_title: "doom 3", original_release_year: 2004, original_platform: "PC", created_at: new Date(), updated_at: new Date() },
  { id: 18, slug: "tomb-raider-1-and-2", title: "Tomb Raider 1 & 2 Classic", normalized_title: "tomb raider 1 & 2 classic", original_release_year: 1996, original_platform: "PS1 / Android", created_at: new Date(), updated_at: new Date() },
  { id: 19, slug: "crazy-taxi", title: "Crazy Taxi", normalized_title: "crazy taxi", original_release_year: 1999, original_platform: "Dreamcast / Android", created_at: new Date(), updated_at: new Date() },
  { id: 20, slug: "am2r", title: "Another Metroid 2 Remake (AM2R)", normalized_title: "another metroid 2 remake (am2r)", original_release_year: 2016, original_platform: "PC / Android", created_at: new Date(), updated_at: new Date() },
  { id: 21, slug: "fahrenheit-indigo-prophecy", title: "Fahrenheit: Indigo Prophecy", normalized_title: "fahrenheit: indigo prophecy", original_release_year: 2005, original_platform: "PS2 / Android", created_at: new Date(), updated_at: new Date() },
  { id: 22, slug: "star-wars-jedi-knight-ii", title: "Star Wars Jedi Knight II: Jedi Outcast", normalized_title: "star wars jedi knight ii: jedi outcast", original_release_year: 2002, original_platform: "PC", created_at: new Date(), updated_at: new Date() },
  { id: 23, slug: "heroes-of-might-and-magic-iii", title: "Heroes of Might and Magic III", normalized_title: "heroes of might and magic iii", original_release_year: 1999, original_platform: "PC", created_at: new Date(), updated_at: new Date() },
  { id: 24, slug: "star-wars-kotor", title: "Star Wars: Knights of the Old Republic", normalized_title: "star wars: knights of the old republic", original_release_year: 2003, original_platform: "Xbox / PC / Android", created_at: new Date(), updated_at: new Date() }
];

export const FALLBACK_PROJECTS: any[] = [
  {
    id: 1,
    game_id: 1,
    slug: "gta-san-andreas-vita",
    display_name: "Grand Theft Auto: San Andreas Vita",
    current_stage: "released",
    lifecycle: "active",
    summary: "Native ARM wrapper port of the Android build with custom OpenGL ES shaders.",
    playability_notes: "Completable from start to finish with full audio, cutscenes and physical controls.",
    performance_notes: "Solid 30 FPS with occasional drops during heavy weather/traffic. 960x544 resolution.",
    first_seen_at: new Date(Date.now() - 300 * 86400000),
    last_activity_at: new Date(Date.now() - 2 * 86400000),
    released_at: new Date(Date.now() - 250 * 86400000),
    is_featured: true,
    is_archived: false,
    game_title: "Grand Theft Auto: San Andreas",
    original_platform: "PS2 / Android",
    original_release_year: 2004,
    technologies: ["ARMv7 Wrapper", "OpenGL ES 2.0", "vitaGL"],
    developers: [{ id: 1, role: "lead", display_name: "TheFloW", slug: "theflow" }, { id: 2, role: "maintainer", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 2,
    game_id: 2,
    slug: "max-payne-vita",
    display_name: "Max Payne Vita",
    current_stage: "playable",
    lifecycle: "active",
    summary: "Port based on Android ARMv7 binary with vitaGL acceleration.",
    playability_notes: "Full story campaign is playable. Bullet time and comic cutscenes functional.",
    performance_notes: "Runs at smooth 30 FPS lock with MSAA 4x enabled.",
    first_seen_at: new Date(Date.now() - 400 * 86400000),
    last_activity_at: new Date(Date.now() - 5 * 86400000),
    released_at: new Date(Date.now() - 350 * 86400000),
    is_featured: true,
    is_archived: false,
    game_title: "Max Payne",
    original_platform: "PC / Android",
    original_release_year: 2001,
    technologies: ["ARMv7 Wrapper", "vitaGL"],
    developers: [{ id: 1, role: "lead", display_name: "TheFloW", slug: "theflow" }]
  },
  {
    id: 3,
    game_id: 3,
    slug: "fallout-2-ce-vita",
    display_name: "Fallout 2 Community Edition",
    current_stage: "playable",
    lifecycle: "active",
    summary: "Open-source recreation of Fallout 2 engine compiled natively for PlayStation Vita.",
    playability_notes: "Fully playable. Supports custom touchscreen touch-controls for mouse cursor emulation.",
    performance_notes: "Smooth 60 FPS in exploration and combat.",
    first_seen_at: new Date(Date.now() - 150 * 86400000),
    last_activity_at: new Date(Date.now() - 1 * 86400000),
    released_at: new Date(Date.now() - 100 * 86400000),
    is_featured: true,
    is_archived: false,
    game_title: "Fallout 2",
    original_platform: "PC",
    original_release_year: 1998,
    technologies: ["Native C++"],
    developers: [{ id: 3, role: "lead", display_name: "alexbatalov", slug: "alexbatalov" }]
  },
  {
    id: 4,
    game_id: 4,
    slug: "hollow-knight-vita",
    display_name: "Hollow Knight Vita Port",
    current_stage: "booting",
    lifecycle: "active",
    summary: "C# / Unity decompilation and native rebuild targeting Vita homebrew SDK.",
    playability_notes: "Currently boots into menu and renders title screens. Asset loader optimization in progress.",
    performance_notes: "Early WIP, unoptimized framerate.",
    first_seen_at: new Date(Date.now() - 60 * 86400000),
    last_activity_at: new Date(Date.now() - 1 * 86400000),
    released_at: null,
    is_featured: true,
    is_archived: false,
    game_title: "Hollow Knight",
    original_platform: "PC",
    original_release_year: 2017,
    technologies: ["Unity C# Rebuild"],
    developers: [{ id: 7, role: "lead", display_name: "patnosDD", slug: "patnosdd" }]
  },
  {
    id: 5,
    game_id: 5,
    slug: "devilutionx-vita",
    display_name: "DevilutionX Diablo",
    current_stage: "released",
    lifecycle: "active",
    summary: "Cross-platform Diablo engine port with multiplayer and high-res scaling.",
    playability_notes: "100% playable, includes Hellfire expansion support and co-op LAN.",
    performance_notes: "Rock solid 60 FPS.",
    first_seen_at: new Date(Date.now() - 500 * 86400000),
    last_activity_at: new Date(Date.now() - 15 * 86400000),
    released_at: new Date(Date.now() - 400 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Diablo (DevilutionX)",
    original_platform: "PC",
    original_release_year: 1996,
    technologies: ["Native C++"],
    developers: [{ id: 2, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 6,
    game_id: 6,
    slug: "sm64-vita",
    display_name: "Super Mario 64 Vita",
    current_stage: "released",
    lifecycle: "active",
    summary: "Decompiled Super Mario 64 PC port compiled natively for PlayStation Vita.",
    playability_notes: "Completely playable with full 120 star completion.",
    performance_notes: "Runs at flawless 60 FPS at native 960x544.",
    first_seen_at: new Date(Date.now() - 600 * 86400000),
    last_activity_at: new Date(Date.now() - 30 * 86400000),
    released_at: new Date(Date.now() - 550 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Super Mario 64",
    original_platform: "N64",
    original_release_year: 1996,
    technologies: ["Native C++"],
    developers: [{ id: 4, role: "lead", display_name: "fgsfds", slug: "fgsfds" }]
  },
  {
    id: 7,
    game_id: 7,
    slug: "gta-vice-city-vita",
    display_name: "Grand Theft Auto: Vice City Vita",
    current_stage: "released",
    lifecycle: "active",
    summary: "Open-source reVC reverse engineered engine ported natively with vitaGL.",
    playability_notes: "Full game story playable from intro to end credits. Full radio stations functional.",
    performance_notes: "Smooth 30 FPS at native 960x544 resolution.",
    first_seen_at: new Date(Date.now() - 450 * 86400000),
    last_activity_at: new Date(Date.now() - 4 * 86400000),
    released_at: new Date(Date.now() - 380 * 86400000),
    is_featured: true,
    is_archived: false,
    game_title: "Grand Theft Auto: Vice City",
    original_platform: "PS2 / Android",
    original_release_year: 2002,
    technologies: ["Reverse-Engineered Engine", "vitaGL"],
    developers: [{ id: 1, role: "lead", display_name: "TheFloW", slug: "theflow" }, { id: 2, role: "maintainer", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 8,
    game_id: 8,
    slug: "gta-iii-vita",
    display_name: "Grand Theft Auto III (re3-vita)",
    current_stage: "released",
    lifecycle: "active",
    summary: "Native port of re3 reverse engineered GTA III source code with custom mipmapping.",
    playability_notes: "Completely playable. Audio and physics fully synced.",
    performance_notes: "Stable 30 FPS across all three islands.",
    first_seen_at: new Date(Date.now() - 550 * 86400000),
    last_activity_at: new Date(Date.now() - 10 * 86400000),
    released_at: new Date(Date.now() - 500 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Grand Theft Auto III",
    original_platform: "PS2 / Android",
    original_release_year: 2001,
    technologies: ["Reverse-Engineered Engine", "vitaGL"],
    developers: [{ id: 1, role: "lead", display_name: "TheFloW", slug: "theflow" }, { id: 2, role: "maintainer", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 9,
    game_id: 9,
    slug: "bully-vita",
    display_name: "Bully: Anniversary Edition Vita",
    current_stage: "playable",
    lifecycle: "active",
    summary: "Android ARMv7 wrapper port with custom texture compression.",
    playability_notes: "Most story missions fully playable. Mini-games and classes functional.",
    performance_notes: "Around 25-30 FPS depending on scene complexity.",
    first_seen_at: new Date(Date.now() - 350 * 86400000),
    last_activity_at: new Date(Date.now() - 3 * 86400000),
    released_at: new Date(Date.now() - 280 * 86400000),
    is_featured: true,
    is_archived: false,
    game_title: "Bully: Anniversary Edition",
    original_platform: "PS2 / Android",
    original_release_year: 2006,
    technologies: ["ARMv7 Wrapper", "vitaGL"],
    developers: [{ id: 1, role: "lead", display_name: "TheFloW", slug: "theflow" }]
  },
  {
    id: 10,
    game_id: 10,
    slug: "simpsons-hit-and-run-vita",
    display_name: "The Simpsons: Hit & Run Vita",
    current_stage: "in_game",
    lifecycle: "active",
    summary: "Reverse-engineered port of Simpsons Hit and Run compiled for PlayStation Vita.",
    playability_notes: "Loads into gameplay, vehicle physics active, audio playback functioning.",
    performance_notes: "Targeting 30 FPS, occasional stutter in open world zones.",
    first_seen_at: new Date(Date.now() - 90 * 86400000),
    last_activity_at: new Date(Date.now() - 1 * 86400000),
    released_at: null,
    is_featured: true,
    is_archived: false,
    game_title: "The Simpsons: Hit & Run",
    original_platform: "PS2 / GameCube",
    original_release_year: 2003,
    technologies: ["Reverse-Engineered Engine"],
    developers: [{ id: 5, role: "lead", display_name: "Zeno99", slug: "zeno99" }]
  },
  {
    id: 11,
    game_id: 11,
    slug: "fallout-1-ce-vita",
    display_name: "Fallout 1 Community Edition",
    current_stage: "playable",
    lifecycle: "active",
    summary: "Open-source Fallout 1 engine reimplementation ported natively to Vita.",
    playability_notes: "Entire wasteland questline playable with touchscreen cursor controls.",
    performance_notes: "Solid 60 FPS.",
    first_seen_at: new Date(Date.now() - 200 * 86400000),
    last_activity_at: new Date(Date.now() - 8 * 86400000),
    released_at: new Date(Date.now() - 140 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Fallout 1",
    original_platform: "PC",
    original_release_year: 1997,
    technologies: ["Native C++"],
    developers: [{ id: 3, role: "lead", display_name: "alexbatalov", slug: "alexbatalov" }]
  },
  {
    id: 12,
    game_id: 12,
    slug: "dead-space-mobile-vita",
    display_name: "Dead Space Mobile Vita",
    current_stage: "released",
    lifecycle: "active",
    summary: "Native ARM wrapper port of the classic iOS/Android Dead Space mobile campaign.",
    playability_notes: "Complete campaign completable with twin-stick aiming mapped to Vita analogs.",
    performance_notes: "Locked 30 FPS with high-res textures.",
    first_seen_at: new Date(Date.now() - 320 * 86400000),
    last_activity_at: new Date(Date.now() - 6 * 86400000),
    released_at: new Date(Date.now() - 260 * 86400000),
    is_featured: true,
    is_archived: false,
    game_title: "Dead Space Mobile",
    original_platform: "Android / iOS",
    original_release_year: 2011,
    technologies: ["ARMv7 Wrapper", "vitaGL"],
    developers: [{ id: 1, role: "lead", display_name: "TheFloW", slug: "theflow" }, { id: 2, role: "maintainer", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 13,
    game_id: 13,
    slug: "mass-effect-infiltrator-vita",
    display_name: "Mass Effect Infiltrator Vita",
    current_stage: "playable",
    lifecycle: "active",
    summary: "ARMv7 Android wrapper port with dual analog controls and vitaGL rendering.",
    playability_notes: "Story campaign missions playable.",
    performance_notes: "Runs at 30 FPS with post-processing shaders.",
    first_seen_at: new Date(Date.now() - 240 * 86400000),
    last_activity_at: new Date(Date.now() - 12 * 86400000),
    released_at: new Date(Date.now() - 180 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Mass Effect Infiltrator",
    original_platform: "Android / iOS",
    original_release_year: 2012,
    technologies: ["ARMv7 Wrapper", "vitaGL"],
    developers: [{ id: 2, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 14,
    game_id: 14,
    slug: "sonic-mania-vita",
    display_name: "Sonic Mania Vita",
    current_stage: "released",
    lifecycle: "active",
    summary: "Decompilation port of Sonic Mania engine compiled for ARM Cortex-A9.",
    playability_notes: "100% playable, all zones, special stages and save system working.",
    performance_notes: "Flawless 60 FPS.",
    first_seen_at: new Date(Date.now() - 420 * 86400000),
    last_activity_at: new Date(Date.now() - 20 * 86400000),
    released_at: new Date(Date.now() - 360 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Sonic Mania",
    original_platform: "PC",
    original_release_year: 2017,
    technologies: ["Native C++", "Reverse-Engineered Engine"],
    developers: [{ id: 6, role: "lead", display_name: "Rubberduckycooly", slug: "rubberduckycooly" }]
  },
  {
    id: 15,
    game_id: 15,
    slug: "halflife-vitaxash3d",
    display_name: "Half-Life (VitaXash3D)",
    current_stage: "released",
    lifecycle: "active",
    summary: "Xash3D FWGS engine port running the original Half-Life goldsrc game and expansions.",
    playability_notes: "Black Mesa campaign and Opposing Force / Blue Shift expansions fully playable.",
    performance_notes: "Smooth 60 FPS.",
    first_seen_at: new Date(Date.now() - 650 * 86400000),
    last_activity_at: new Date(Date.now() - 35 * 86400000),
    released_at: new Date(Date.now() - 600 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Half-Life",
    original_platform: "PC",
    original_release_year: 1998,
    technologies: ["Native C++"],
    developers: [{ id: 4, role: "lead", display_name: "fgsfds", slug: "fgsfds" }]
  },
  {
    id: 16,
    game_id: 16,
    slug: "rtcw-vita",
    display_name: "Return to Castle Wolfenstein (iortcw)",
    current_stage: "released",
    lifecycle: "active",
    summary: "Open-source iortcw port for Vita with dual analog aiming and gyro support.",
    playability_notes: "Single-player campaign completely playable.",
    performance_notes: "Runs at 60 FPS at native resolution.",
    first_seen_at: new Date(Date.now() - 500 * 86400000),
    last_activity_at: new Date(Date.now() - 25 * 86400000),
    released_at: new Date(Date.now() - 450 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Return to Castle Wolfenstein",
    original_platform: "PC",
    original_release_year: 2001,
    technologies: ["Native C++", "vitaGL"],
    developers: [{ id: 2, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 17,
    game_id: 17,
    slug: "doom-3-vita",
    display_name: "Doom 3 (D3wasm / dhewm3)",
    current_stage: "playable",
    lifecycle: "active",
    summary: "dhewm3 open source engine port bringing Doom 3 to Vita hardware.",
    playability_notes: "Base campaign is playable from start to Mars underground.",
    performance_notes: "25-30 FPS in heavy combat, dynamic lighting enabled.",
    first_seen_at: new Date(Date.now() - 280 * 86400000),
    last_activity_at: new Date(Date.now() - 9 * 86400000),
    released_at: new Date(Date.now() - 200 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Doom 3",
    original_platform: "PC",
    original_release_year: 2004,
    technologies: ["Native C++", "vitaGL"],
    developers: [{ id: 2, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 18,
    game_id: 18,
    slug: "tomb-raider-classic-vita",
    display_name: "Tomb Raider 1 & 2 Classic Vita",
    current_stage: "released",
    lifecycle: "active",
    summary: "Native wrapper ports of the Android remaster releases of Tomb Raider 1 & 2.",
    playability_notes: "Full classic adventures completable with modern button layouts.",
    performance_notes: "Locked 60 FPS.",
    first_seen_at: new Date(Date.now() - 360 * 86400000),
    last_activity_at: new Date(Date.now() - 18 * 86400000),
    released_at: new Date(Date.now() - 310 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Tomb Raider 1 & 2 Classic",
    original_platform: "PS1 / Android",
    original_release_year: 1996,
    technologies: ["ARMv7 Wrapper", "vitaGL"],
    developers: [{ id: 2, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 19,
    game_id: 19,
    slug: "crazy-taxi-vita",
    display_name: "Crazy Taxi Classic Vita",
    current_stage: "playable",
    lifecycle: "active",
    summary: "ARMv7 wrapper of the mobile Crazy Taxi port with original soundtrack restoration.",
    playability_notes: "Arcade and Original modes playable.",
    performance_notes: "Smooth 60 FPS.",
    first_seen_at: new Date(Date.now() - 310 * 86400000),
    last_activity_at: new Date(Date.now() - 14 * 86400000),
    released_at: new Date(Date.now() - 270 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Crazy Taxi",
    original_platform: "Dreamcast / Android",
    original_release_year: 1999,
    technologies: ["ARMv7 Wrapper", "vitaGL"],
    developers: [{ id: 2, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 20,
    game_id: 20,
    slug: "am2r-vita",
    display_name: "AM2R: Return of Samus Vita",
    current_stage: "released",
    lifecycle: "active",
    summary: "GameMaker Studio native ARM runner port of Another Metroid 2 Remake v1.5.5.",
    playability_notes: "Entire planet SR388 exploration and ending completable.",
    performance_notes: "Solid 60 FPS lock.",
    first_seen_at: new Date(Date.now() - 520 * 86400000),
    last_activity_at: new Date(Date.now() - 40 * 86400000),
    released_at: new Date(Date.now() - 480 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Another Metroid 2 Remake (AM2R)",
    original_platform: "PC / Android",
    original_release_year: 2016,
    technologies: ["ARMv7 Wrapper"],
    developers: [{ id: 2, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 21,
    game_id: 21,
    slug: "fahrenheit-vita",
    display_name: "Fahrenheit: Indigo Prophecy Vita",
    current_stage: "playable",
    lifecycle: "active",
    summary: "ARMv7 Android wrapper with touch gesture emulation and gamepad binding.",
    playability_notes: "Story branches playable.",
    performance_notes: "30 FPS with remastered 3D models.",
    first_seen_at: new Date(Date.now() - 260 * 86400000),
    last_activity_at: new Date(Date.now() - 7 * 86400000),
    released_at: new Date(Date.now() - 210 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Fahrenheit: Indigo Prophecy",
    original_platform: "PS2 / Android",
    original_release_year: 2005,
    technologies: ["ARMv7 Wrapper", "vitaGL"],
    developers: [{ id: 2, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 22,
    game_id: 22,
    slug: "jedi-outcast-vita",
    display_name: "Star Wars Jedi Knight II: Jedi Outcast",
    current_stage: "playable",
    lifecycle: "active",
    summary: "openjk engine port with lightsaber combat and Force powers mapped to dual analogs.",
    playability_notes: "Single player campaign playable.",
    performance_notes: "30-45 FPS.",
    first_seen_at: new Date(Date.now() - 430 * 86400000),
    last_activity_at: new Date(Date.now() - 19 * 86400000),
    released_at: new Date(Date.now() - 370 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Star Wars Jedi Knight II: Jedi Outcast",
    original_platform: "PC",
    original_release_year: 2002,
    technologies: ["Native C++", "vitaGL"],
    developers: [{ id: 2, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 23,
    game_id: 23,
    slug: "homm3-vcmi-vita",
    display_name: "Heroes of Might & Magic III (VCMI)",
    current_stage: "playable",
    lifecycle: "active",
    summary: "VCMI engine port for HOMM3 with touch cursor controls.",
    playability_notes: "Custom scenarios and campaign maps playable.",
    performance_notes: "Turn-based strategy performance is smooth.",
    first_seen_at: new Date(Date.now() - 480 * 86400000),
    last_activity_at: new Date(Date.now() - 22 * 86400000),
    released_at: new Date(Date.now() - 410 * 86400000),
    is_featured: false,
    is_archived: false,
    game_title: "Heroes of Might and Magic III",
    original_platform: "PC",
    original_release_year: 1999,
    technologies: ["Native C++"],
    developers: [{ id: 2, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 24,
    game_id: 24,
    slug: "kotor-vita",
    display_name: "Star Wars: KOTOR Vita",
    current_stage: "early_wip",
    lifecycle: "active",
    summary: "Community reverse-engineering and ARM wrapper research for Knights of the Old Republic.",
    playability_notes: "Shader compilation and memory allocator mapping in progress.",
    performance_notes: "Early technical research.",
    first_seen_at: new Date(Date.now() - 70 * 86400000),
    last_activity_at: new Date(Date.now() - 1 * 86400000),
    released_at: null,
    is_featured: true,
    is_archived: false,
    game_title: "Star Wars: Knights of the Old Republic",
    original_platform: "Xbox / PC / Android",
    original_release_year: 2003,
    technologies: ["ARMv7 Wrapper"],
    developers: [{ id: 2, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  }
];

export const FALLBACK_DEVELOPERS: any[] = [
  { id: 1, slug: "theflow", display_name: "TheFloW", description: "Renowned PlayStation Vita security researcher and port developer (GTA, Max Payne, Bully).", is_known_developer: true, identities: [{ provider: "reddit", username: "TheOfficialFloW" }], projects: [{ id: 1, slug: "gta-san-andreas-vita", display_name: "Grand Theft Auto: San Andreas Vita", current_stage: "released", lifecycle: "active", summary: "Native ARM wrapper port of the Android build with custom OpenGL ES shaders.", role: "lead" }, { id: 2, slug: "max-payne-vita", display_name: "Max Payne Vita", current_stage: "playable", lifecycle: "active", summary: "Port based on Android ARMv7 binary with vitaGL acceleration.", role: "lead" }, { id: 7, slug: "gta-vice-city-vita", display_name: "Grand Theft Auto: Vice City Vita", current_stage: "released", lifecycle: "active", summary: "Open-source reVC reverse engineered engine ported natively with vitaGL.", role: "lead" }, { id: 8, slug: "gta-iii-vita", display_name: "Grand Theft Auto III (re3-vita)", current_stage: "released", lifecycle: "active", summary: "Native port of re3 reverse engineered GTA III source code.", role: "lead" }, { id: 9, slug: "bully-vita", display_name: "Bully: Anniversary Edition Vita", current_stage: "playable", lifecycle: "active", summary: "Android ARMv7 wrapper port with custom texture compression.", role: "lead" }, { id: 12, slug: "dead-space-mobile-vita", display_name: "Dead Space Mobile Vita", current_stage: "released", lifecycle: "active", summary: "Native ARM wrapper port of the Dead Space mobile campaign.", role: "lead" }] },
  { id: 2, slug: "rinnegatamante", display_name: "Rinnegatamante", description: "Creator of vitaGL and prolific Vita homebrew porter responsible for over 30 engine ports.", is_known_developer: true, identities: [{ provider: "reddit", username: "Rinnegatamante" }], projects: [{ id: 1, slug: "gta-san-andreas-vita", display_name: "Grand Theft Auto: San Andreas Vita", current_stage: "released", lifecycle: "active", summary: "Native ARM wrapper port of the Android build with custom OpenGL ES shaders.", role: "maintainer" }, { id: 5, slug: "devilutionx-vita", display_name: "DevilutionX Diablo", current_stage: "released", lifecycle: "active", summary: "Cross-platform Diablo engine port with multiplayer and high-res scaling.", role: "lead" }, { id: 7, slug: "gta-vice-city-vita", display_name: "Grand Theft Auto: Vice City Vita", current_stage: "released", lifecycle: "active", summary: "Open-source reVC reverse engineered engine ported natively with vitaGL.", role: "maintainer" }, { id: 8, slug: "gta-iii-vita", display_name: "Grand Theft Auto III (re3-vita)", current_stage: "released", lifecycle: "active", summary: "Native port of re3 reverse engineered GTA III source code.", role: "maintainer" }, { id: 12, slug: "dead-space-mobile-vita", display_name: "Dead Space Mobile Vita", current_stage: "released", lifecycle: "active", summary: "Native ARM wrapper port of the Dead Space mobile campaign.", role: "maintainer" }, { id: 13, slug: "mass-effect-infiltrator-vita", display_name: "Mass Effect Infiltrator Vita", current_stage: "playable", lifecycle: "active", summary: "ARMv7 Android wrapper port with dual analog controls.", role: "lead" }, { id: 16, slug: "rtcw-vita", display_name: "Return to Castle Wolfenstein (iortcw)", current_stage: "released", lifecycle: "active", summary: "Open-source iortcw port for Vita.", role: "lead" }, { id: 17, slug: "doom-3-vita", display_name: "Doom 3 (D3wasm / dhewm3)", current_stage: "playable", lifecycle: "active", summary: "dhewm3 open source engine port bringing Doom 3 to Vita.", role: "lead" }, { id: 18, slug: "tomb-raider-classic-vita", display_name: "Tomb Raider 1 & 2 Classic Vita", current_stage: "released", lifecycle: "active", summary: "Native wrapper ports of the Android remaster releases.", role: "lead" }, { id: 19, slug: "crazy-taxi-vita", display_name: "Crazy Taxi Classic Vita", current_stage: "playable", lifecycle: "active", summary: "ARMv7 wrapper of the mobile Crazy Taxi port.", role: "lead" }, { id: 20, slug: "am2r-vita", display_name: "AM2R: Return of Samus Vita", current_stage: "released", lifecycle: "active", summary: "GameMaker Studio native ARM runner port of AM2R v1.5.5.", role: "lead" }, { id: 21, slug: "fahrenheit-vita", display_name: "Fahrenheit: Indigo Prophecy Vita", current_stage: "playable", lifecycle: "active", summary: "ARMv7 Android wrapper with touch gesture emulation.", role: "lead" }, { id: 22, slug: "jedi-outcast-vita", display_name: "Star Wars Jedi Knight II: Jedi Outcast", current_stage: "playable", lifecycle: "active", summary: "openjk engine port with lightsaber combat.", role: "lead" }, { id: 23, slug: "homm3-vcmi-vita", display_name: "Heroes of Might & Magic III (VCMI)", current_stage: "playable", lifecycle: "active", summary: "VCMI engine port for HOMM3 with touch cursor controls.", role: "lead" }, { id: 24, slug: "kotor-vita", display_name: "Star Wars: KOTOR Vita", current_stage: "early_wip", lifecycle: "active", summary: "Community reverse-engineering and ARM wrapper research for KOTOR.", role: "lead" }] },
  { id: 3, slug: "alexbatalov", display_name: "alexbatalov", description: "Developer of Fallout 1 & 2 Community Edition engines.", is_known_developer: true, identities: [{ provider: "reddit", username: "alexbatalov" }], projects: [{ id: 3, slug: "fallout-2-ce-vita", display_name: "Fallout 2 Community Edition", current_stage: "playable", lifecycle: "active", summary: "Open-source recreation of Fallout 2 engine compiled natively for PlayStation Vita.", role: "lead" }, { id: 11, slug: "fallout-1-ce-vita", display_name: "Fallout 1 Community Edition", current_stage: "playable", lifecycle: "active", summary: "Open-source Fallout 1 engine reimplementation ported natively to Vita.", role: "lead" }] },
  { id: 4, slug: "fgsfds", display_name: "fgsfds", description: "Homebrew developer responsible for numerous high-profile engine ports on Vita (SM64, Half-Life).", is_known_developer: true, identities: [{ provider: "reddit", username: "fgsfds" }], projects: [{ id: 6, slug: "sm64-vita", display_name: "Super Mario 64 Vita", current_stage: "released", lifecycle: "active", summary: "Decompiled Super Mario 64 PC port compiled natively for PlayStation Vita.", role: "lead" }, { id: 15, slug: "halflife-vitaxash3d", display_name: "Half-Life (VitaXash3D)", current_stage: "released", lifecycle: "active", summary: "Xash3D FWGS engine port running the original Half-Life and expansions.", role: "lead" }] },
  { id: 5, slug: "zeno99", display_name: "Zeno99", description: "Reverse engineering enthusiast working on Simpsons Hit & Run and open source decompilations.", is_known_developer: true, identities: [{ provider: "reddit", username: "Zeno99" }], projects: [{ id: 10, slug: "simpsons-hit-and-run-vita", display_name: "The Simpsons: Hit & Run Vita", current_stage: "in_game", lifecycle: "active", summary: "Reverse-engineered port of Simpsons Hit and Run.", role: "lead" }] },
  { id: 6, slug: "rubberduckycooly", display_name: "Rubberduckycooly", description: "Decompilation specialist contributing to Retro Engine Sonic ports.", is_known_developer: true, identities: [{ provider: "reddit", username: "Rubberduckycooly" }], projects: [{ id: 14, slug: "sonic-mania-vita", display_name: "Sonic Mania Vita", current_stage: "released", lifecycle: "active", summary: "Decompilation port of Sonic Mania engine for ARM Cortex-A9.", role: "lead" }] },
  { id: 7, slug: "patnosdd", display_name: "patnosDD", description: "Homebrew developer leading the C# / Unity decompilation port of Hollow Knight.", is_known_developer: true, identities: [{ provider: "reddit", username: "patnosDD" }], projects: [{ id: 4, slug: "hollow-knight-vita", display_name: "Hollow Knight Vita Port", current_stage: "booting", lifecycle: "active", summary: "C# / Unity decompilation and native rebuild targeting Vita homebrew SDK.", role: "lead" }] }
];

export const FALLBACK_UPDATES: any[] = [
  {
    id: "upd_1",
    port_project_id: 1,
    project_slug: "gta-san-andreas-vita",
    project_display_name: "Grand Theft Auto: San Andreas Vita",
    developer_display_name: "TheFloW",
    developer_slug: "theflow",
    event_type: "release",
    title: "GTA: San Andreas v2.1 Performance Patch Released",
    summary: "Added custom shader cache to reduce stuttering during flight missions and improved analog stick sensitivity.",
    event_at: new Date(Date.now() - 2 * 86400000),
    verification_level: "developer_direct",
    sources: [{ source_item_id: "src_gta_sa", relationship: "primary", canonical_url: "https://www.reddit.com/r/vitahacks/comments/l1x92z/release_grand_theft_auto_san_andreas_for_ps_vita/" }]
  },
  {
    id: "upd_2",
    port_project_id: 3,
    project_slug: "fallout-2-ce-vita",
    project_display_name: "Fallout 2 Community Edition",
    developer_display_name: "alexbatalov",
    developer_slug: "alexbatalov",
    event_type: "playability_progress",
    title: "Touchscreen mouse cursor acceleration implemented",
    summary: "Added native touch gesture recognition for inventory management and pipboy navigation.",
    event_at: new Date(Date.now() - 1 * 86400000),
    verification_level: "developer_direct",
    sources: [{ source_item_id: "src_fo2", relationship: "primary", canonical_url: "https://www.reddit.com/r/vitahacks/comments/q1910a/release_fallout_2_ce_ps_vita_port/" }]
  },
  {
    id: "upd_3",
    port_project_id: 4,
    project_slug: "hollow-knight-vita",
    project_display_name: "Hollow Knight Vita Port",
    developer_display_name: "patnosDD",
    developer_slug: "patnosdd",
    event_type: "first_boot",
    title: "Hollow Knight title screen now boots on real hardware",
    summary: "Unity C# decompiled bytecode successfully translated to native ARM ELF and rendered initial splash screens.",
    event_at: new Date(Date.now() - 1 * 86400000),
    verification_level: "developer_direct",
    sources: [{ source_item_id: "src_hk", relationship: "primary", canonical_url: "https://www.reddit.com/r/VitaPiracy/comments/p89z1a/hollow_knight_vita_port_status_update_first_boot/" }]
  },
  {
    id: "upd_4",
    port_project_id: 9,
    project_slug: "bully-vita",
    project_display_name: "Bully: Anniversary Edition Vita",
    developer_display_name: "TheFloW",
    developer_slug: "theflow",
    event_type: "technical_progress",
    title: "Bully 60fps unlocked camera patch & memory fix",
    summary: "Resolved out-of-memory crashes when entering Bullworth Academy main building.",
    event_at: new Date(Date.now() - 3 * 86400000),
    verification_level: "developer_direct",
    sources: [{ source_item_id: "src_bully", relationship: "primary", canonical_url: "https://www.reddit.com/r/vitahacks/comments/m6a11e/release_bully_anniversary_edition_ps_vita_port/" }]
  },
  {
    id: "upd_5",
    port_project_id: 10,
    project_slug: "simpsons-hit-and-run-vita",
    project_display_name: "The Simpsons: Hit & Run Vita",
    developer_display_name: "Zeno99",
    developer_slug: "zeno99",
    event_type: "first_in_game",
    title: "The Simpsons: Hit & Run enters playable gameplay on real hardware",
    summary: "Vehicle physics and Springfield Level 1 geometry successfully rendered at native resolution.",
    event_at: new Date(Date.now() - 1 * 86400000),
    verification_level: "community_report",
    sources: [{ source_item_id: "src_simpsons", relationship: "primary", canonical_url: "https://www.reddit.com/r/VitaPiracy/comments/simps1/simpsons_hit_and_run_first_in_game_milestone_reached/" }]
  },
  {
    id: "upd_6",
    port_project_id: 24,
    project_slug: "kotor-vita",
    project_display_name: "Star Wars: KOTOR Vita",
    developer_display_name: "Rinnegatamante",
    developer_slug: "rinnegatamante",
    event_type: "project_announced",
    title: "KOTOR Vita port research & shader mapping commenced",
    summary: "Initial research into compiling Android bio-engine shaders and handling memory constraints.",
    event_at: new Date(Date.now() - 1 * 86400000),
    verification_level: "developer_direct",
    sources: [{ source_item_id: "src_kotor", relationship: "primary", canonical_url: "https://www.reddit.com/r/vitahacks/comments/kotor1/star_wars_kotor_vita_port_research_and_shader_compilation/" }]
  }
];

