import type { Game } from "../types";

export const FALLBACK_GAMES: Game[] = [
  { id: 1, slug: "medal-of-honor-allied-assault", title: "Medal of Honor: Allied Assault (OpenMoHAA)", normalized_title: "medal of honor: allied assault (openmohaa)", original_release_year: 2002, original_platform: "PC", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 2, slug: "super-smash-bros-melee", title: "Super Smash Bros. Melee", normalized_title: "super smash bros. melee", original_release_year: 2001, original_platform: "GameCube / Decomp", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 3, slug: "hollow-knight", title: "Hollow Knight", normalized_title: "hollow knight", original_release_year: 2017, original_platform: "PC / Unity", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 4, slug: "zelda-twilight-princess", title: "The Legend of Zelda: Twilight Princess", normalized_title: "the legend of zelda: twilight princess", original_release_year: 2006, original_platform: "GameCube / Wii Decomp", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 5, slug: "portal-vita", title: "Portal (Source Engine / N64 Decomp)", normalized_title: "portal (source engine / n64 decomp)", original_release_year: 2007, original_platform: "PC", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 6, slug: "spider-man-total-mayhem", title: "Spider-Man: Total Mayhem", normalized_title: "spider-man: total mayhem", original_release_year: 2010, original_platform: "Android ARMv7", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 7, slug: "the-simpsons-hit-and-run", title: "The Simpsons: Hit & Run", normalized_title: "the simpsons: hit & run", original_release_year: 2003, original_platform: "PS2 / GameCube", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 8, slug: "star-wars-kotor", title: "Star Wars: Knights of the Old Republic", normalized_title: "star wars: knights of the old republic", original_release_year: 2003, original_platform: "Xbox / PC / Android", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 9, slug: "baldurs-gate-dark-alliance", title: "Baldur's Gate: Dark Alliance", normalized_title: "baldur's gate: dark alliance", original_release_year: 2001, original_platform: "PS2 / GameCube", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 10, slug: "need-for-speed-hot-pursuit", title: "Need for Speed: Hot Pursuit", normalized_title: "need for speed: hot pursuit", original_release_year: 2010, original_platform: "Android", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 11, slug: "class-of-09", title: "Class of '09", normalized_title: "class of '09", original_release_year: 2021, original_platform: "PC / Ren'Py", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 12, slug: "renpy-8-runtime", title: "Ren'Py 8 Runtime (Python 3.11)", normalized_title: "ren'py 8 runtime (python 3.11)", original_release_year: 2024, original_platform: "Multiplatform Engine", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 13, slug: "zelda-ship-of-harkinian", title: "Zelda: Ship of Harkinian (Ocarina of Time)", normalized_title: "zelda: ship of harkinian (ocarina of time)", original_release_year: 1998, original_platform: "N64 / PC Decomp", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 14, slug: "slingshot-racing", title: "Slingshot Racing", normalized_title: "slingshot racing", original_release_year: 2012, original_platform: "Android / iOS", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 15, slug: "fallout-2", title: "Fallout 2 Community Edition", normalized_title: "fallout 2 community edition", original_release_year: 1998, original_platform: "PC", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 16, slug: "render96-sm64", title: "Render96 HD SM64 Vita", normalized_title: "render96 hd sm64 vita", original_release_year: 2020, original_platform: "PC Decomp", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 17, slug: "celeste-classic", title: "Celeste Classic Vita", normalized_title: "celeste classic vita", original_release_year: 2016, original_platform: "PICO-8 / C", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 18, slug: "cave-story-nxengine", title: "Cave Story (NXEngine-evo)", normalized_title: "cave story (nxengine-evo)", original_release_year: 2004, original_platform: "PC", created_at: new Date('2026-09-17T15:34:00.000Z'), updated_at: new Date('2026-09-17T15:34:00.000Z') },
  { id: 19, slug: "renegade-vita-demo-release", title: "Renegade Vita - Demo Release", normalized_title: "renegade vita - demo release", original_release_year: null, original_platform: "Unknown", created_at: new Date('2026-09-15T03:40:12.000Z'), updated_at: new Date('2026-09-17T15:34:20.988Z') }
  ,{ id: 20, slug: "rc-cars", title: "RC Cars", normalized_title: "rc cars", original_release_year: null, original_platform: "PC", created_at: new Date('2026-09-18T11:09:43.000Z'), updated_at: new Date('2026-09-18T15:20:00.000Z') }
  ,{ id: 21, slug: "diablo-ii-lord-of-destruction", title: "Diablo II: Lord of Destruction", normalized_title: "diablo ii: lord of destruction", original_release_year: 2001, original_platform: "PC", created_at: new Date('2026-09-17T22:27:31.000Z'), updated_at: new Date('2026-09-17T22:27:31.000Z') }
  ,{ id: 22, slug: "call-of-duty-zombies", title: "Call of Duty: Zombies", normalized_title: "call of duty: zombies", original_release_year: 2009, original_platform: "iOS", created_at: new Date('2026-09-18T07:54:45.000Z'), updated_at: new Date('2026-09-18T07:54:45.000Z') }
];

export const FALLBACK_PROJECTS: any[] = [
  {
    id: 1,
    game_id: 1,
    slug: "openmohaa-vita",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/1tapf2b/wip_openmohaa_on_ps_vita_medal_of_honor_allied/",
    display_name: "Medal of Honor: Allied Assault (OpenMoHAA)",
    current_stage: "in_game",
    lifecycle: "active",
    summary: "Native PlayStation Vita port of OpenMoHAA. Geometry, sound engine, mission scripts, and player controls functioning.",
    playability_notes: "Boots straight into gameplay. Normandy and training grounds render properly. Collision and sound effects active.",
    performance_notes: "5–15 FPS in heavy outdoor combat scenes. Memory allocation optimization and shader pipeline tuning in progress.",
    first_seen_at: new Date('2026-06-19T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-16T15:34:00.000Z'),
    released_at: null,
    is_featured: true,
    is_archived: false,
    game_title: "Medal of Honor: Allied Assault (OpenMoHAA)",
    original_platform: "PC",
    original_release_year: 2002,
    technologies: ["OpenMoHAA", "Native C++", "vitaGL"],
    developers: [{ id: 1, role: "lead", display_name: "OpenMoHAA Team", slug: "openmohaa-team" }]
  },
  {
    id: 2,
    game_id: 2,
    slug: "smash-melee-vita",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/1wivnp0/super_smash_melee/",
    display_name: "Super Smash Bros. Melee Vita",
    current_stage: "in_game",
    lifecycle: "active",
    summary: "Two independent experimental Melee ports are active: rob1n994 is moving Aurora to native SceGXM/vitaGL, while zm2283145 has an early decompilation-based build running in gameplay.",
    playability_notes: "The zm2283145 build reaches gameplay with models and animations loaded from the original game data. The rob1n994 build is demonstrated on Vita hardware and has a public source repository.",
    performance_notes: "Both builds remain work in progress. Rendering, textures, framebuffer effects, particles, stability, and substantial performance optimization are still required.",
    first_seen_at: new Date('2026-07-04T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-17T14:31:58.000Z'),
    released_at: null,
    is_featured: true,
    is_archived: false,
    game_title: "Super Smash Bros. Melee",
    original_platform: "GameCube / Decomp",
    original_release_year: 2001,
    technologies: ["Aurora", "SceGXM", "vitaGL", "Decompilation", "Native C++"],
    developers: [
      { id: 13, role: "lead", display_name: "rob1n994", slug: "rob1n994" },
      { id: 14, role: "lead", display_name: "zm2283145", slug: "zm2283145" }
    ]
  },
  {
    id: 3,
    game_id: 3,
    slug: "hollow-knight-vita",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/17eneu2/upcoming_hollow_knight_ps_vita_port_wip/",
    display_name: "Hollow Knight Vita Port",
    current_stage: "booting",
    lifecycle: "active",
    summary: "Complete C# / Unity decompilation translated into native ARM bytecode for the PS Vita.",
    playability_notes: "Boots into title screen and menu. Dirtmouth intro zone loads with audio and initial player animations.",
    performance_notes: "Memory exhaustion crashes during room transitions. Asset cache streaming currently being rewritten.",
    first_seen_at: new Date('2026-05-20T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-14T15:34:00.000Z'),
    released_at: null,
    is_featured: true,
    is_archived: false,
    game_title: "Hollow Knight",
    original_platform: "PC / Unity",
    original_release_year: 2017,
    technologies: ["Unity C# Decomp", "Native ARM"],
    developers: [{ id: 3, role: "lead", display_name: "patnosDD", slug: "patnosdd" }]
  },
  {
    id: 4,
    game_id: 4,
    slug: "zelda-twilight-princess-vita",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/1w9ys9f/the_new_psvita_ports/",
    display_name: "Zelda: Twilight Princess Vita",
    current_stage: "early_wip",
    lifecycle: "active",
    summary: "Reverse-engineering project evaluating GC/Wii decompiled shaders on Vita hardware.",
    playability_notes: "Ordon Village test geometry compiled. Early rendering experiments show models and skybox.",
    performance_notes: "15–20 FPS in static test scenes. High RAM footprint requiring custom texture compression.",
    first_seen_at: new Date('2026-07-19T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-15T15:34:00.000Z'),
    released_at: null,
    is_featured: true,
    is_archived: false,
    game_title: "The Legend of Zelda: Twilight Princess",
    original_platform: "GameCube / Wii Decomp",
    original_release_year: 2006,
    technologies: ["Decompilation", "vitaGL"],
    developers: [{ id: 2, role: "lead", display_name: "Community Decomp Team", slug: "community-decomp" }]
  },
  {
    id: 5,
    game_id: 5,
    slug: "portal-vita",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/16l8h0m/portal_vita_status/",
    display_name: "Portal Vita Port",
    current_stage: "in_game",
    lifecycle: "active",
    summary: "Portal mechanics and chamber physics ported via standalone engine recreation.",
    playability_notes: "Test Chambers 00 through 05 playable. Portal gun firing, momentum calculation, and cube physics active.",
    performance_notes: "Smooth 30 FPS indoors; dips to 20 FPS when looking through recursive dual portals.",
    first_seen_at: new Date('2026-06-09T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-13T15:34:00.000Z'),
    released_at: null,
    is_featured: true,
    is_archived: false,
    game_title: "Portal (Source Engine / N64 Decomp)",
    original_platform: "PC",
    original_release_year: 2007,
    technologies: ["Native C++", "OpenGL ES"],
    developers: [{ id: 4, role: "lead", display_name: "DanielSant0s", slug: "danielsant0s" }]
  },
  {
    id: 6,
    game_id: 6,
    slug: "spider-man-total-mayhem-vita",
    reddit_url: "https://www.reddit.com/r/VitaPiracy/comments/1ij1vzf/how_to_port_android_games/",
    display_name: "Spider-Man: Total Mayhem Vita",
    current_stage: "in_game",
    lifecycle: "active",
    summary: "Gameloft action brawler reverse-engineered and wrapped with dual analog combat controls.",
    playability_notes: "New York city brawler levels load and combat mechanics are operational on real hardware.",
    performance_notes: "Runs at 25–30 FPS in combat arenas; shader cleanup in progress.",
    first_seen_at: new Date('2026-07-14T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-16T15:34:00.000Z'),
    released_at: null,
    is_featured: true,
    is_archived: false,
    game_title: "Spider-Man: Total Mayhem",
    original_platform: "Android ARMv7",
    original_release_year: 2010,
    technologies: ["ARMv7 Wrapper", "vitaGL"],
    developers: [{ id: 5, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 7,
    game_id: 7,
    slug: "simpsons-hit-and-run-vita",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/126a9bf/release_ship_of_harkinian_vita_port/",
    display_name: "The Simpsons: Hit & Run Vita",
    current_stage: "in_game",
    lifecycle: "active",
    summary: "Reverse-engineered port of Simpsons Hit and Run compiled for PlayStation Vita.",
    playability_notes: "Vehicle physics active, audio playback functioning, Springfield Level 1 geometry rendered.",
    performance_notes: "Targeting 30 FPS. Stuttering observed during rapid vehicular streaming.",
    first_seen_at: new Date('2026-05-30T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-14T15:34:00.000Z'),
    released_at: null,
    is_featured: true,
    is_archived: false,
    game_title: "The Simpsons: Hit & Run",
    original_platform: "PS2 / GameCube",
    original_release_year: 2003,
    technologies: ["Reverse-Engineered Engine"],
    developers: [{ id: 6, role: "lead", display_name: "Zeno99", slug: "zeno99" }]
  },
  {
    id: 8,
    game_id: 8,
    slug: "kotor-vita",
    reddit_url: "https://www.reddit.com/r/VitaPiracy/comments/1iuoe4u/rinnegatamante_is_going_all_out/",
    display_name: "Star Wars: KOTOR Vita",
    current_stage: "early_wip",
    lifecycle: "active",
    summary: "Community reverse-engineering and ARM wrapper research for Knights of the Old Republic.",
    playability_notes: "Shader compilation and memory allocator mapping in progress.",
    performance_notes: "Early technical research stage.",
    first_seen_at: new Date('2026-06-29T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-15T15:34:00.000Z'),
    released_at: null,
    is_featured: true,
    is_archived: false,
    game_title: "Star Wars: Knights of the Old Republic",
    original_platform: "Xbox / PC / Android",
    original_release_year: 2003,
    technologies: ["ARMv7 Wrapper"],
    developers: [{ id: 5, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 9,
    game_id: 9,
    slug: "baldurs-gate-dark-alliance-vita",
    reddit_url: "https://www.reddit.com/r/VitaPiracy/comments/1inclw4/any_listcollection_of_homebrew_fanmade_ports_of/",
    display_name: "Baldur's Gate: Dark Alliance Vita",
    current_stage: "research",
    lifecycle: "active",
    summary: "Engine evaluation and reverse-engineering research for the Snowblind Studios engine on Vita.",
    playability_notes: "Analyzing Android ARMv7 binary symbol tables and memory models.",
    performance_notes: "Pre-alpha technical analysis.",
    first_seen_at: new Date('2026-08-08T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-15T15:34:00.000Z'),
    released_at: null,
    is_featured: true,
    is_archived: false,
    game_title: "Baldur's Gate: Dark Alliance",
    original_platform: "PS2 / GameCube",
    original_release_year: 2001,
    technologies: ["ARMv7 Wrapper", "Reverse-Engineering"],
    developers: [{ id: 5, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 10,
    game_id: 10,
    slug: "nfs-hot-pursuit-vita",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/18zdtep/new_port_psvita_hot_pursuit/",
    display_name: "Need for Speed: Hot Pursuit Vita",
    current_stage: "playable",
    lifecycle: "active",
    summary: "ARM wrapper port of NFS Hot Pursuit mobile with analog steering and custom Vita shaders.",
    playability_notes: "Career events and cops vs racers races fully operational with hardware acceleration.",
    performance_notes: "Smooth 30 FPS across sprint and pursuit courses.",
    first_seen_at: new Date('2025-07-24T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-14T15:34:00.000Z'),
    released_at: new Date('2025-08-13T15:34:00.000Z'),
    is_featured: false,
    is_archived: false,
    game_title: "Need for Speed: Hot Pursuit",
    original_platform: "Android",
    original_release_year: 2010,
    technologies: ["ARMv7 Wrapper", "vitaGL"],
    developers: [{ id: 7, role: "lead", display_name: "hatoving", slug: "hatoving" }]
  },
  {
    id: 11,
    game_id: 11,
    slug: "class-of-09-vita",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/192k7s9/the_class_of_09_vita_port_is_finally_released/",
    display_name: "Class of '09 Vita Port",
    current_stage: "released",
    lifecycle: "active",
    summary: "Native port of the viral dark comedy visual novel powered by the updated Ren'Py Vita engine.",
    playability_notes: "100% completable. All routes, voice acting, cutscenes, and graduation endings verified.",
    performance_notes: "Instant route transitions, flawless audio and touch/button dialogue progression.",
    first_seen_at: new Date('2026-03-11T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-15T15:34:00.000Z'),
    released_at: new Date('2026-05-20T15:34:00.000Z'),
    is_featured: false,
    is_archived: false,
    game_title: "Class of '09",
    original_platform: "PC / Ren'Py",
    original_release_year: 2021,
    technologies: ["Ren'Py Vita", "Python 3"],
    developers: [{ id: 8, role: "lead", display_name: "SonicMastr", slug: "sonicmastr" }]
  },
  {
    id: 12,
    game_id: 12,
    slug: "renpy-8-runtime-engine",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/1h4yhyi/release_renpy_vita_8_port/",
    display_name: "Ren'Py 8 Vita Engine Runtime",
    current_stage: "released",
    lifecycle: "active",
    summary: "Major architectural breakthrough bringing Python 3.11 and modern Ren'Py 8.x games natively to Vita.",
    playability_notes: "Unlocks dozens of modern visual novels previously incompatible with Python 2 runtimes.",
    performance_notes: "Significantly lower memory usage and accelerated text rendering.",
    first_seen_at: new Date('2026-02-09T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-16T15:34:00.000Z'),
    released_at: new Date('2026-06-24T15:34:00.000Z'),
    is_featured: false,
    is_archived: false,
    game_title: "Ren'Py 8 Runtime (Python 3.11)",
    original_platform: "Multiplatform Engine",
    original_release_year: 2024,
    technologies: ["Python 3.11", "SDL2", "vitaGL"],
    developers: [{ id: 8, role: "lead", display_name: "SonicMastr", slug: "sonicmastr" }]
  },
  {
    id: 13,
    game_id: 13,
    slug: "zelda-ship-of-harkinian-vita",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/126a9bf/release_ship_of_harkinian_vita_port/",
    display_name: "Zelda: Ship of Harkinian (OOT)",
    current_stage: "playable",
    lifecycle: "active",
    summary: "Direct native Vita build of the Harbour Masters reverse-engineered Ocarina of Time decompilation.",
    playability_notes: "Full campaign completable with high FPS, widescreen 16:9 viewport, and gyro aiming.",
    performance_notes: "Solid 30-60 FPS depending on enhancement settings.",
    first_seen_at: new Date('2025-09-22T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-13T15:34:00.000Z'),
    released_at: new Date('2026-01-20T15:34:00.000Z'),
    is_featured: false,
    is_archived: false,
    game_title: "Zelda: Ship of Harkinian (Ocarina of Time)",
    original_platform: "N64 / PC Decomp",
    original_release_year: 1998,
    technologies: ["Native C++", "libultraship", "vitaGL"],
    developers: [{ id: 9, role: "lead", display_name: "Northfear", slug: "northfear" }]
  },
  {
    id: 14,
    game_id: 14,
    slug: "slingshot-racing-vita",
    reddit_url: "https://www.reddit.com/r/VitaPiracy/comments/1iuoe4u/rinnegatamante_is_going_all_out/",
    display_name: "Slingshot Racing Vita",
    current_stage: "released",
    lifecycle: "active",
    summary: "One-touch steampunk racer ported via ARMv7 wrapper with full physical trigger integration.",
    playability_notes: "All tournament cups and multi-lap trials 100% playable.",
    performance_notes: "Locked 60 FPS at native OLED resolution.",
    first_seen_at: new Date('2026-06-14T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-15T15:34:00.000Z'),
    released_at: new Date('2026-08-03T15:34:00.000Z'),
    is_featured: false,
    is_archived: false,
    game_title: "Slingshot Racing",
    original_platform: "Android / iOS",
    original_release_year: 2012,
    technologies: ["ARMv7 Wrapper", "vitaGL"],
    developers: [{ id: 5, role: "lead", display_name: "Rinnegatamante", slug: "rinnegatamante" }]
  },
  {
    id: 15,
    game_id: 15,
    slug: "fallout-2-ce-vita",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/q1910a/release_fallout_2_ce_ps_vita_port/",
    display_name: "Fallout 2 Community Edition",
    current_stage: "playable",
    lifecycle: "active",
    summary: "Open-source recreation of Fallout 2 engine compiled natively for PlayStation Vita.",
    playability_notes: "Fully playable with touch controls for cursor emulation.",
    performance_notes: "Smooth 60 FPS in exploration and combat.",
    first_seen_at: new Date('2026-04-10T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-12T15:34:00.000Z'),
    released_at: new Date('2026-06-09T15:34:00.000Z'),
    is_featured: false,
    is_archived: false,
    game_title: "Fallout 2 Community Edition",
    original_platform: "PC",
    original_release_year: 1998,
    technologies: ["Native C++"],
    developers: [{ id: 10, role: "lead", display_name: "alexbatalov", slug: "alexbatalov" }]
  },
  {
    id: 16,
    game_id: 16,
    slug: "render96-sm64-hd-vita",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/1whm4hp/smash_bros_melee_vita/",
    display_name: "Render96 HD SM64 Vita",
    current_stage: "released",
    lifecycle: "active",
    summary: "High-fidelity SGI CGI pre-rendered asset recreation of Super Mario 64 ported natively to Vita.",
    playability_notes: "Full game playable with updated CGI models and remastered stereo audio.",
    performance_notes: "30-60 FPS with custom texture compression.",
    first_seen_at: new Date('2025-11-11T15:34:00.000Z'),
    last_activity_at: new Date('2026-09-02T15:34:00.000Z'),
    released_at: new Date('2026-03-01T15:34:00.000Z'),
    is_featured: false,
    is_archived: false,
    game_title: "Render96 HD SM64 Vita",
    original_platform: "PC Decomp",
    original_release_year: 2020,
    technologies: ["Native C++", "OpenGL"],
    developers: [{ id: 11, role: "lead", display_name: "fgsfds", slug: "fgsfds" }]
  },
  {
    id: 17,
    game_id: 17,
    slug: "celeste-classic-vita",
    reddit_url: "https://www.reddit.com/r/VitaPiracy/comments/1inclw4/any_listcollection_of_homebrew_fanmade_ports_of/",
    display_name: "Celeste Classic Vita",
    current_stage: "released",
    lifecycle: "active",
    summary: "C-rewrite of the original PICO-8 Celeste prototype compiled directly for PlayStation Vita.",
    playability_notes: "All 30 mountain levels and strawberries 100% completable.",
    performance_notes: "Locked 60 FPS with pixel-perfect integer scaling.",
    first_seen_at: new Date('2025-08-23T15:34:00.000Z'),
    last_activity_at: new Date('2026-08-18T15:34:00.000Z'),
    released_at: new Date('2025-09-22T15:34:00.000Z'),
    is_featured: false,
    is_archived: false,
    game_title: "Celeste Classic Vita",
    original_platform: "PICO-8 / C",
    original_release_year: 2016,
    technologies: ["Native C", "SDL2"],
    developers: [{ id: 12, role: "lead", display_name: "MyLegGuy", slug: "mylegguy" }]
  },
  {
    id: 18,
    game_id: 18,
    slug: "cave-story-evo-vita",
    reddit_url: "https://www.reddit.com/r/VitaPiracy/comments/1inclw4/any_listcollection_of_homebrew_fanmade_ports_of/",
    display_name: "Cave Story (NXEngine-evo)",
    current_stage: "released",
    lifecycle: "active",
    summary: "Complete open-source NXEngine-evo upgrade supporting remastered music and wide aspect ratio.",
    playability_notes: "All story endings, Hell Sanctuary, and Curly story mode fully playable.",
    performance_notes: "Rock solid 60 FPS.",
    first_seen_at: new Date('2025-04-15T15:34:00.000Z'),
    last_activity_at: new Date('2026-08-28T15:34:00.000Z'),
    released_at: new Date('2025-06-24T15:34:00.000Z'),
    is_featured: false,
    is_archived: false,
    game_title: "Cave Story (NXEngine-evo)",
    original_platform: "PC",
    original_release_year: 2004,
    technologies: ["Native C++", "SDL2"],
    developers: [{ id: 9, role: "lead", display_name: "Northfear", slug: "northfear" }]
  },
  {
    id: 19,
    game_id: 19,
    slug: "renegade-vita-demo-release",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/1wgp613/renegade_vita_demo_release/",
    display_name: "Renegade Vita - Demo Release",
    current_stage: "announced",
    lifecycle: "active",
    summary: "Detected by the scanner on r/vitahacks. Awaiting independent verification on hardware.",
    playability_notes: null,
    performance_notes: null,
    first_seen_at: new Date('2026-09-15T03:40:12.000Z'),
    last_activity_at: new Date('2026-09-17T15:34:20.988Z'),
    released_at: null,
    is_featured: false,
    is_archived: false,
    verification: "detected",
    game_title: "Renegade Vita - Demo Release",
    original_platform: "Unknown",
    original_release_year: null,
    technologies: [],
    developers: []
  }
  ,{
    id: 20,
    game_id: 20,
    slug: "rc-cars-vita",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/1wjn8zg/rc_cars_port_progress/",
    display_name: "RC Cars",
    current_stage: "playable",
    lifecycle: "active",
    summary: "Native RC Cars port by antoxa2584x, published with source at github.com/antoxa2584x/rc_cars_vita. The progress post reports PC save file support, an implemented progression system, local multiplayer and an in-game interface.",
    playability_notes: "Developer reports progression, local multiplayer and the in-game interface as implemented, with PC save files compatible.",
    performance_notes: null,
    first_seen_at: new Date('2026-09-18T11:09:43.000Z'),
    last_activity_at: new Date('2026-09-18T11:09:43.000Z'),
    released_at: null,
    is_featured: false,
    is_archived: false,
    verification: "developer_direct",
    game_title: "RC Cars",
    original_platform: "PC",
    original_release_year: null,
    technologies: [],
    developers: []
  }
  ,{
    id: 21,
    game_id: 21,
    slug: "d2vita",
    reddit_url: "https://www.reddit.com/r/VitaPiracy/comments/1wj8dvz/d2vita_is_here_diablo_ii_lord_of_destruction/",
    display_name: "D2Vita (Diablo II: Lord of Destruction)",
    current_stage: "released",
    lifecycle: "active",
    summary: "Public release that runs the original Diablo II: Lord of Destruction 1.14d Windows build on PS Vita. The x86 game code executes through winx86, a compatibility layer with an x86 to ARMv7 dynamic recompiler, while the Windows APIs are replaced by native Vita implementations.",
    playability_notes: "Runs the original 1.14d build rather than a rewritten engine. Performance varies between 10 and 25 FPS while the cache is being built, then settles around 20 to 25 FPS.",
    performance_notes: "Diablo II itself is capped at 25 FPS, so the settled 20 to 25 FPS range is close to the original ceiling.",
    first_seen_at: new Date('2026-09-17T22:27:31.000Z'),
    last_activity_at: new Date('2026-09-17T22:27:31.000Z'),
    released_at: new Date('2026-09-17T22:27:31.000Z'),
    is_featured: false,
    is_archived: false,
    verification: "developer_direct",
    game_title: "Diablo II: Lord of Destruction",
    original_platform: "PC",
    original_release_year: 2001,
    technologies: ["winx86", "x86 to ARMv7 recompiler", "Native Windows API layer"],
    developers: []
  }
  ,{
    id: 22,
    game_id: 22,
    slug: "cod-zombies-ios-loader",
    reddit_url: "https://www.reddit.com/r/vitahacks/comments/1wjjx7w/a_bounty_that_deserves_more_visibility/",
    display_name: "Call of Duty: Zombies (iOS)",
    current_stage: "announced",
    lifecycle: "active",
    summary: "A community bounty is funding an effort to bring the iOS release of Call of Duty: Zombies to Vita, tied to the iOS loader devnoname120 is developing. The thread names Metal Gear Solid Touch as another iOS title the same loader could open up. No build exists yet.",
    playability_notes: null,
    performance_notes: null,
    first_seen_at: new Date('2026-09-18T07:54:45.000Z'),
    last_activity_at: new Date('2026-09-18T07:54:45.000Z'),
    released_at: null,
    is_featured: false,
    is_archived: false,
    verification: "community_report",
    game_title: "Call of Duty: Zombies",
    original_platform: "iOS",
    original_release_year: 2009,
    technologies: ["iOS loader"],
    developers: []
  }
];

export const FALLBACK_DEVELOPERS: any[] = [
  { id: 1, slug: "openmohaa-team", display_name: "OpenMoHAA Team", description: "Homebrew engineering group porting Medal of Honor Allied Assault natively to modern platforms and Vita.", is_known_developer: true, identities: [{ provider: "reddit", username: "OpenMoHAA" }], projects: [] },
  { id: 2, slug: "community-decomp", display_name: "Community Decomp Team", description: "Collaborative decompilation contributors researching GameCube/Wii native execution on ARM Vita.", is_known_developer: true, identities: [{ provider: "reddit", username: "vitahacks" }], projects: [] },
  { id: 3, slug: "patnosdd", display_name: "patnosDD", description: "Developer leading the C# / Unity decompilation native pipeline for Hollow Knight on Vita.", is_known_developer: true, identities: [{ provider: "reddit", username: "patnosDD" }], projects: [] },
  { id: 4, slug: "danielsant0s", display_name: "DanielSant0s", description: "Port developer reverse engineering Portal physics and chamber rendering for handhelds.", is_known_developer: true, identities: [{ provider: "reddit", username: "DanielSant0s" }], projects: [] },
  { id: 5, slug: "rinnegatamante", display_name: "Rinnegatamante", description: "Prolific Vita homebrew architect, vitaGL creator, and developer of numerous Android wrappers.", is_known_developer: true, identities: [{ provider: "reddit", username: "Rinnegatamante" }], projects: [] },
  { id: 6, slug: "zeno99", display_name: "Zeno99", description: "Reverse engineering specialist working on The Simpsons: Hit & Run engine recreation.", is_known_developer: true, identities: [{ provider: "reddit", username: "Zeno99" }], projects: [] },
  { id: 7, slug: "hatoving", display_name: "hatoving", description: "Homebrew porter who brought Need for Speed: Hot Pursuit to PlayStation Vita via ARM wrapper.", is_known_developer: true, identities: [{ provider: "reddit", username: "hatoving" }], projects: [] },
  { id: 8, slug: "sonicmastr", display_name: "SonicMastr", description: "Engine architect behind Ren'Py 8 Vita runtime (Python 3.11) and Class of '09.", is_known_developer: true, identities: [{ provider: "reddit", username: "SonicMastr" }], projects: [] },
  { id: 9, slug: "northfear", display_name: "Northfear", description: "Veteran homebrew developer behind native ports of Ship of Harkinian and NXEngine-evo.", is_known_developer: true, identities: [{ provider: "reddit", username: "Northfear" }], projects: [] },
  { id: 10, slug: "alexbatalov", display_name: "alexbatalov", description: "Developer of Fallout 1 & 2 Community Edition engines.", is_known_developer: true, identities: [{ provider: "reddit", username: "alexbatalov" }], projects: [] },
  { id: 11, slug: "fgsfds", display_name: "fgsfds", description: "Homebrew developer responsible for Render96 HD SM64 and numerous engine ports.", is_known_developer: true, identities: [{ provider: "reddit", username: "fgsfds" }], projects: [] },
  { id: 12, slug: "mylegguy", display_name: "MyLegGuy", description: "Programmer who created the C-rewrite of Celeste Classic for handheld systems.", is_known_developer: true, identities: [{ provider: "reddit", username: "MyLegGuy" }], projects: [] },
  { id: 13, slug: "rob1n994", display_name: "rob1n994", description: "Developer porting the Aurora-based Melee project to native SceGXM and vitaGL on PS Vita.", is_known_developer: true, identities: [{ provider: "reddit", username: "rob1n994" }, { provider: "github", username: "robin994" }], projects: [] },
  { id: 14, slug: "zm2283145", display_name: "zm2283145", description: "Developer of an independent experimental Melee Vita port with in-game rendering.", is_known_developer: true, identities: [{ provider: "reddit", username: "zm2283145" }], projects: [] }
];

export const FALLBACK_UPDATES: any[] = [
  {
    id: "upd_mohaa",
    port_project_id: 1,
    project_slug: "openmohaa-vita",
    project_display_name: "Medal of Honor: Allied Assault (OpenMoHAA)",
    developer_display_name: "OpenMoHAA Team",
    developer_slug: "openmohaa-team",
    event_type: "first_in_game",
    title: "[WIP] OpenMoHAA on PS Vita — Medal of Honor: Allied Assault in-game progress",
    summary: "Normandy beach level boots on PS Vita Fat with functioning geometry, sound effects, and player movement. Currently averaging 5-15 FPS.",
    event_at: new Date('2026-09-16T15:34:00.000Z'),
    verification_level: "developer_direct",
    sources: [{ source_item_id: "src_mohaa", relationship: "primary", canonical_url: "https://www.reddit.com/r/vitahacks/comments/1tapf2b/wip_openmohaa_on_ps_vita_medal_of_honor_allied/" }]
  },
  {
    id: "upd_melee",
    port_project_id: 2,
    project_slug: "smash-melee-vita",
    project_display_name: "Super Smash Bros. Melee Vita",
    developer_display_name: "Community Decomp Team",
    developer_slug: "community-decomp",
    event_type: "first_boot",
    title: "Smash Bros Melee Vita — Fighter selection screen boots on hardware",
    summary: "Decompiled GameCube pipeline successfully renders character models and UI. In-game physics and RAM optimizations currently in development.",
    event_at: new Date('2026-09-15T15:34:00.000Z'),
    verification_level: "community_report",
    sources: [{ source_item_id: "src_melee", relationship: "primary", canonical_url: "https://www.reddit.com/r/vitahacks/comments/1whm4hp/smash_bros_melee_vita/" }]
  },
  {
    id: "upd_melee_robin994",
    port_project_id: 2,
    project_slug: "smash-melee-vita",
    project_display_name: "Super Smash Bros. Melee Vita",
    developer_display_name: "rob1n994",
    developer_slug: "rob1n994",
    event_type: "technical_progress",
    title: "Super Smash Melee — second Vita port moves Aurora to SceGXM and vitaGL",
    summary: "rob1n994 publicly demonstrated an independent Melee port and opened its source while native SceGXM/vitaGL performance and fidelity work continues.",
    event_at: new Date('2026-09-17T14:31:58.000Z'),
    verification_level: "developer_direct",
    sources: [{ source_item_id: "src_melee_robin994", relationship: "primary", canonical_url: "https://www.reddit.com/r/vitahacks/comments/1wivnp0/super_smash_melee/" }]
  },
  {
    id: "upd_zelda_tp",
    port_project_id: 4,
    project_slug: "zelda-twilight-princess-vita",
    project_display_name: "Zelda: Twilight Princess Vita",
    developer_display_name: "Community Decomp Team",
    developer_slug: "community-decomp",
    event_type: "technical_progress",
    title: "Twilight Princess decompilation test builds surfaced on r/vitahacks",
    summary: "Early rendering tests running at 15-20 FPS in Ordon Village. Investigating custom texture compression to fit within Vita's 512MB RAM.",
    event_at: new Date('2026-09-15T15:34:00.000Z'),
    verification_level: "community_report",
    sources: [{ source_item_id: "src_tp", relationship: "primary", canonical_url: "https://www.reddit.com/r/vitahacks/comments/1w9ys9f/the_new_psvita_ports/" }]
  },
  {
    id: "upd_spiderman",
    port_project_id: 6,
    project_slug: "spider-man-total-mayhem-vita",
    project_display_name: "Spider-Man: Total Mayhem Vita",
    developer_display_name: "Rinnegatamante",
    developer_slug: "rinnegatamante",
    event_type: "first_in_game",
    title: "Spider-Man: Total Mayhem loads into gameplay on real hardware",
    summary: "Gameloft ARMv7 wrapper milestone reached with full Manhattan brawler combat and dual analog camera controls active.",
    event_at: new Date('2026-09-14T15:34:00.000Z'),
    verification_level: "developer_direct",
    sources: [{ source_item_id: "src_spiderman", relationship: "primary", canonical_url: "https://www.reddit.com/r/VitaPiracy/comments/1ij1vzf/how_to_port_android_games/" }]
  },
  {
    id: "upd_portal",
    port_project_id: 5,
    project_slug: "portal-vita",
    project_display_name: "Portal Vita Port",
    developer_display_name: "DanielSant0s",
    developer_slug: "danielsant0s",
    event_type: "playability_progress",
    title: "Portal Vita: Test Chambers 00-05 playable with working physics",
    summary: "Dual portal rendering, momentum calculation, and weighted companion cube mechanics functioning smoothly at 30 FPS.",
    event_at: new Date('2026-09-13T15:34:00.000Z'),
    verification_level: "developer_direct",
    sources: [{ source_item_id: "src_portal", relationship: "primary", canonical_url: "https://www.reddit.com/r/vitahacks/search/?q=Portal&restrict_sr=1" }]
  },
  {
    id: "upd_class09",
    port_project_id: 11,
    project_slug: "class-of-09-vita",
    project_display_name: "Class of '09 Vita Port",
    developer_display_name: "SonicMastr",
    developer_slug: "sonicmastr",
    event_type: "release",
    title: "The Class of '09 Vita Port is finally released!",
    summary: "Full commercial VN ported natively with complete voice acting, gallery unlocks, and touchscreen/button controls.",
    event_at: new Date('2026-09-12T15:34:00.000Z'),
    verification_level: "developer_direct",
    sources: [{ source_item_id: "src_class09", relationship: "primary", canonical_url: "https://www.reddit.com/r/vitahacks/comments/192k7s9/the_class_of_09_vita_port_is_finally_released/" }]
  },
  {
    id: "upd_renpy8",
    port_project_id: 12,
    project_slug: "renpy-8-runtime-engine",
    project_display_name: "Ren'Py 8 Vita Engine Runtime",
    developer_display_name: "SonicMastr",
    developer_slug: "sonicmastr",
    event_type: "release",
    title: "[RELEASE] Ren'Py Vita 8 port with Python 3.11 support",
    summary: "Enables modern visual novels previously impossible on older Python 2 Vita runtimes with optimized RAM utilization.",
    event_at: new Date('2026-09-11T15:34:00.000Z'),
    verification_level: "developer_direct",
    sources: [{ source_item_id: "src_renpy8", relationship: "primary", canonical_url: "https://www.reddit.com/r/vitahacks/comments/1h4yhyi/release_renpy_vita_8_port/" }]
  },
  {
    id: "upd_nfs",
    port_project_id: 10,
    project_slug: "nfs-hot-pursuit-vita",
    project_display_name: "Need for Speed: Hot Pursuit Vita",
    developer_display_name: "hatoving",
    developer_slug: "hatoving",
    event_type: "release",
    title: "[NEW PORT] PS Vita Hot Pursuit released",
    summary: "Full ARM wrapper release with smooth career progression, cop pursuit missions, and custom graphical pipeline.",
    event_at: new Date('2026-09-10T15:34:00.000Z'),
    verification_level: "developer_direct",
    sources: [{ source_item_id: "src_nfs", relationship: "primary", canonical_url: "https://www.reddit.com/r/vitahacks/comments/18zdtep/new_port_psvita_hot_pursuit/" }]
  }
  ,{
    id: "upd_rc_cars",
    port_project_id: 20,
    project_slug: "rc-cars-vita",
    project_display_name: "RC Cars",
    developer_display_name: "antoxa2584x",
    developer_slug: "antoxa2584x",
    event_type: "technical_progress",
    title: "RC Cars port progress",
    summary: "Developer reports PC save file support, implemented progression, local multiplayer and an in-game interface, with source published on GitHub.",
    event_at: new Date('2026-09-18T11:09:43.000Z'),
    verification_level: "developer_direct",
    sources: [{ source_item_id: "src_rc_cars", relationship: "primary", canonical_url: "https://www.reddit.com/r/vitahacks/comments/1wjn8zg/rc_cars_port_progress/" }]
  }
  ,{
    id: "upd_d2vita",
    port_project_id: 21,
    project_slug: "d2vita",
    project_display_name: "D2Vita (Diablo II: Lord of Destruction)",
    developer_display_name: "Realistic-Pitch-3467",
    developer_slug: "realistic-pitch-3467",
    event_type: "release",
    title: "D2Vita is here — Diablo II: Lord of Destruction running on PS Vita",
    summary: "Public release running the original 1.14d Windows build through winx86, an x86 to ARMv7 dynamic recompiler with native Vita API replacements. Settles around 20 to 25 FPS once its cache is built.",
    event_at: new Date('2026-09-17T22:27:31.000Z'),
    verification_level: "developer_direct",
    sources: [{ source_item_id: "src_d2vita", relationship: "primary", canonical_url: "https://www.reddit.com/r/VitaPiracy/comments/1wj8dvz/d2vita_is_here_diablo_ii_lord_of_destruction/" }]
  }
  ,{
    id: "upd_cod_zombies",
    port_project_id: 22,
    project_slug: "cod-zombies-ios-loader",
    project_display_name: "Call of Duty: Zombies (iOS)",
    developer_display_name: "MajorTom_87",
    developer_slug: "majortom-87",
    event_type: "project_announced",
    title: "Bounty opened for Call of Duty: Zombies on Vita",
    summary: "Community bounty funding work to bring the iOS build of Call of Duty: Zombies to Vita through the iOS loader devnoname120 is developing. Metal Gear Solid Touch is named as another candidate for the same loader.",
    event_at: new Date('2026-09-18T07:54:45.000Z'),
    verification_level: "community_report",
    sources: [{ source_item_id: "src_cod_zombies", relationship: "primary", canonical_url: "https://www.reddit.com/r/vitahacks/comments/1wjjx7w/a_bounty_that_deserves_more_visibility/" }]
  }
];

const MILESTONE_REASONS: Record<string, string> = {
  announced: "Port publicly announced / surfaced in community discussion",
  research: "Reverse-engineering and shader research started",
  early_wip: "First work-in-progress build compiled for ARM",
  booting: "Binary boots to the point of rendering output",
  in_game: "Reached interactive in-game state on real hardware",
  playable: "Playable end to end with working controls and audio",
  completable: "Completable: full progression verified by testers",
  released: "Public release build published"
};

const DERIVED_STAGE_SEQUENCE = [
  "announced",
  "research",
  "early_wip",
  "booting",
  "in_game",
  "playable",
  "completable",
  "released"
];

function deriveStageHistory(project: Record<string, unknown>) {
  const current = String(project.current_stage || "announced");
  const endIndex = DERIVED_STAGE_SEQUENCE.indexOf(current);
  if (endIndex < 0) return [];

  const start = new Date(project.first_seen_at as string | number | Date).getTime();
  const end = new Date(project.last_activity_at as string | number | Date).getTime();
  const span = Math.max(end - start, 0);
  const steps = endIndex + 1;

  return DERIVED_STAGE_SEQUENCE.slice(0, steps).map((stage, index) => {
    const ratio = steps === 1 ? 0 : index / (steps - 1);
    const effective = new Date(start + span * ratio * 0.92);
    return {
      id: Number(project.id) * 10 + index,
      stage,
      effective_at: effective,
      reason: MILESTONE_REASONS[stage] || null
    };
  });
}

FALLBACK_PROJECTS.forEach((project) => {
  if (!project.stage_history || project.stage_history.length === 0) {
    project.stage_history = deriveStageHistory(project);
  }
});
